@DesafioTarget2_HostAddress = http://localhost:5278

POST {{DesafioTarget2_HostAddress}}/desafio2/Solucao/RegistraEstoque
Accept: application/json

{
    "estoque": [
        {
            "codigoProduto": 101,
            "descricaoProduto": "Caneta Azul",
            "estoque": 150
        },
        {
            "codigoProduto": 102,
            "descricaoProduto": "Caderno Universitário",
            "estoque": 75
        },
        {
            "codigoProduto": 103,
            "descricaoProduto": "Borracha Branca",
            "estoque": 200
        },
        {
            "codigoProduto": 104,
            "descricaoProduto": "Lápis Preto HB",
            "estoque": 320
        },
        {
            "codigoProduto": 105,
            "descricaoProduto": "Marcador de Texto Amarelo",
            "estoque": 90
        }
    ]
}

###

POST {{DesafioTarget2_HostAddress}}/desafio2/Solucao/MovimentaEstoque
Accept: application/json

{
    "descricao": "descrição",
    "codigoProduto": 101,
    "quantidade":  5
}